--
-- ARQUIVOIMPORTACAO_OCT  (Table) 
--
CREATE TABLE ARQUIVOIMPORTACAO_OCT
(
  ID_ARQUIVOIMPORTACAO           NUMBER         NOT NULL,
  ARQUIVOIMPORTACAOCAMINHO       VARCHAR2(200 BYTE) NOT NULL,
  ARQUIVOIMPORTACAODATA          DATE           NOT NULL,
  ARQUIVOIMPORTACAOSTATUS        NUMBER,
  ARQUIVOIMPORTACAOQTLINHAS      NUMBER,
  ARQUIVOIMPORTACAOQTLINHASOK    NUMBER,
  ARQUIVOIMPORTACAOQTLINHASERRO  NUMBER,
  ARQUIVOIMPORTACAOTIPO          CHAR(1 BYTE)   NOT NULL,
  ID_LAYOUT                      NUMBER,
  ARQUIVOIMPORTACAORETORNO       VARCHAR2(200 BYTE)
)
TABLESPACE TSDSVA01
PARTITION BY RANGE (ARQUIVOIMPORTACAODATA)
(  
  PARTITION ARQDATA_MENOR_2014 VALUES LESS THAN (TO_DATE(' 2014-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART01,  
  PARTITION ARQDATA_2014 VALUES LESS THAN (TO_DATE(' 2015-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART02,  
  PARTITION ARQDATA_2015 VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART03,  
  PARTITION ARQDATA_2016 VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART04,  
  PARTITION ARQDATA_2017 VALUES LESS THAN (TO_DATE(' 2018-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART05,  
  PARTITION ARQDATA_2018 VALUES LESS THAN (TO_DATE(' 2019-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART06,  
  PARTITION ARQDATA_2019 VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART07,  
  PARTITION ARQDATA_2020 VALUES LESS THAN (TO_DATE(' 2021-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART08,  
  PARTITION ARQDATA_2021 VALUES LESS THAN (TO_DATE(' 2022-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART09,  
  PARTITION ARQDATA_MAIOR_2021 VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART10
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ARQUIVOIMPORTACAO_OCT IS 'Tabela de cabecalho do arquivo de importacao';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ID_ARQUIVOIMPORTACAO IS 'Chave';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ARQUIVOIMPORTACAOCAMINHO IS 'Caminho do arquivo';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ARQUIVOIMPORTACAODATA IS 'Data da importacao';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ARQUIVOIMPORTACAOSTATUS IS 'Status de importacao do arquivo 0-Erro, 1-OK ou 2-Recusado';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ARQUIVOIMPORTACAOQTLINHAS IS 'Qtde. Linhas importadas do arquivo';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ARQUIVOIMPORTACAOQTLINHASOK IS 'Qtde. Linhas importadas com sucesso do arquivo';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ARQUIVOIMPORTACAOQTLINHASERRO IS 'Qtde. Linhas importadas com erro do arquivo';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ARQUIVOIMPORTACAOTIPO IS 'Tipo do Arquivo Importado - C-Cadastro I-Inativacao M-Movimento';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ID_LAYOUT IS 'Identificacao do LayOut';

COMMENT ON COLUMN ARQUIVOIMPORTACAO_OCT.ARQUIVOIMPORTACAORETORNO IS 'Caminho do Arquivo de retorno';


--
-- ARQUIVOIMPORTACAONX1  (Index) 
--
CREATE INDEX ARQUIVOIMPORTACAONX1_OCT ON ARQUIVOIMPORTACAO_OCT
(ARQUIVOIMPORTACAOCAMINHO)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


--
-- ARQUIVOIMPORTACAO_PK  (Index) 
--
CREATE UNIQUE INDEX ARQUIVOIMPORTACAO_OCT_PK ON ARQUIVOIMPORTACAO_OCT
(ID_ARQUIVOIMPORTACAO)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


-- 
-- Non Foreign Key Constraints for Table ARQUIVOIMPORTACAO_OCT 
-- 
ALTER TABLE ARQUIVOIMPORTACAO_OCT ADD (
  CONSTRAINT ARQUIVOIMPORTACAO_OCT_PK
 PRIMARY KEY
 (ID_ARQUIVOIMPORTACAO)
    USING INDEX 
    TABLESPACE TSISVA01);

-- 
-- Foreign Key Constraints for Table ARQUIVOIMPORTACAO_OCT 
-- 
ALTER TABLE ARQUIVOIMPORTACAO_OCT ADD (
  CONSTRAINT ARQUIVOMPORTACAO_FK_LAYOUT 
 FOREIGN KEY (ID_LAYOUT) 
 REFERENCES LAYOUT (ID_LAYOUT));

GRANT DELETE, INSERT, SELECT, UPDATE ON ARQUIVOIMPORTACAO_OCT TO APP_BFFOWN;