--
-- INTERFACECRM_OCT_HIST  (Table) 
--

/**
 * 
 *  Analisar necessidade de criação dessa tabela 
 */
CREATE TABLE INTERFACECRM_OCT_HIST
(
  ANOMES                   NUMBER               DEFAULT TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMM')),
  ID_INTERFACECRM          NUMBER               NOT NULL,
  ID_LOGIMPORTACAO         NUMBER               NOT NULL,
  INTERFACECRMXML          VARCHAR2(4000 BYTE)  NOT NULL,
  INTERFACECRMSTATUS       NUMBER               NOT NULL,
  INTERFACECRMMETODO       NUMBER               NOT NULL,
  INTERFACECRMSESSIONID    NUMBER,
  INTERFACECRMMSG          VARCHAR2(4000 BYTE),
  INTERFACECRMLINHA        VARCHAR2(4000 BYTE),
  INTERFACECRMDATAGERACAO  DATE                 NOT NULL,
  INTERFACECRMDATAENVIO    DATE,
  ID_ARQUIVOIMPORTACAO     NUMBER               NOT NULL
)
TABLESPACE TSISVA01
PARTITION BY RANGE (ANOMES)
(  
  PARTITION ANOMES_1 VALUES LESS THAN (201401)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS01,  
  PARTITION ANOMES_2 VALUES LESS THAN (201501)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS02,  
  PARTITION ANOMES_3 VALUES LESS THAN (201601)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS03,  
  PARTITION ANOMES_4 VALUES LESS THAN (201701)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS04,  
  PARTITION ANOMES_5 VALUES LESS THAN (201801)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS05,  
  PARTITION ANOMES_6 VALUES LESS THAN (201901)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS06,  
  PARTITION ANOMES_7 VALUES LESS THAN (202001)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS07,  
  PARTITION ANOMES_8 VALUES LESS THAN (202101)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS08,  
  PARTITION ANOMES_9 VALUES LESS THAN (202201)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS09,  
  PARTITION ANOMES_10 VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_CONS10
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE INTERFACECRM_OCT_HIST IS 'Tabela de Interface CRM OCT Histórico.';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.ANOMES IS 'Ano mes para controle de particionamento';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.ID_INTERFACECRM IS 'ID da Interface CRM OCT';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.ID_LOGIMPORTACAO IS 'ID da LogImportacao correspondente';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.INTERFACECRMXML IS 'XML da Interface CRM';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.INTERFACECRMSTATUS IS 'Status da Interface CRM - 0-Pendente 1-Enviado 9- Erro';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.INTERFACECRMMETODO IS 'Metodo da Interface CRM - 1-ATIVAR 2-CANCELAR';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.INTERFACECRMSESSIONID IS 'Numero da Sessão da Interface CRM';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.INTERFACECRMMSG IS 'Mensagem de Erro';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.INTERFACECRMLINHA IS 'Linha da Interface CRM';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.INTERFACECRMDATAGERACAO IS 'Data de geração';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.INTERFACECRMDATAENVIO IS 'Data de envio';

COMMENT ON COLUMN INTERFACECRM_OCT_HIST.ID_ARQUIVOIMPORTACAO IS 'Identificação do arquivo';


--
-- INTERFACECRM_HISTNX1  (Index) 
--
CREATE INDEX INTERFACECRM_HISTNX1 ON INTERFACECRM_OCT_HIST
(ID_LOGIMPORTACAO)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


--
-- INTERFACECRM_HISTNX2  (Index) 
--
CREATE INDEX INTERFACECRM_HISTNX2 ON INTERFACECRM_OCT_HIST
(ID_ARQUIVOIMPORTACAO)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


--
-- INTERFACECRM_HISTNX3  (Index) 
--
CREATE INDEX INTERFACECRM_HISTNX3 ON INTERFACECRM_OCT_HIST
(INTERFACECRMDATAGERACAO)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


--
-- INTERFACECRM_HIST_PK  (Index) 
--
CREATE UNIQUE INDEX INTERFACECRM_HIST_PK ON INTERFACECRM_OCT_HIST
(ID_INTERFACECRM)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACECRM_OCT_HIST TO APP_SVAUSR;

