/*  
 * Criação da Tabela Interface CRM OCT
 * */
CREATE TABLE INTERFACECRM_OCT
(
  ID_INTERFACECRM          NUMBER               NOT NULL,
  ID_LOGIMPORTACAO         NUMBER               NOT NULL,
  INTERFACECRMXML          VARCHAR2(4000 BYTE)  NOT NULL,
  INTERFACECRMSTATUS       NUMBER               NOT NULL,
  INTERFACECRMMETODO       NUMBER               NOT NULL,
  INTERFACECRMSESSIONID    NUMBER,
  INTERFACECRMMSG          VARCHAR2(4000 BYTE),
  INTERFACECRMLINHA        VARCHAR2(4000 BYTE),
  INTERFACECRMDATAGERACAO  DATE                 NOT NULL,
  INTERFACECRMDATAENVIO    DATE,
  ID_ARQUIVOIMPORTACAO     NUMBER               NOT NULL
)
TABLESPACE TSDBFF01
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE INTERFACECRM_OCT IS 'Tabela de Interface CRM OCT.';

COMMENT ON COLUMN INTERFACECRM_OCT.ID_INTERFACECRM IS 'ID da Interface CRM OCT';

COMMENT ON COLUMN INTERFACECRM_OCT.ID_LOGIMPORTACAO IS 'ID da LogImportacao correspondente';

COMMENT ON COLUMN INTERFACECRM_OCT.INTERFACECRMXML IS 'XML da Interface CRM OCT';

COMMENT ON COLUMN INTERFACECRM_OCT.INTERFACECRMSTATUS IS 'Status da Interface CRM - 0-Pendente 1-Enviado 9- Erro';

COMMENT ON COLUMN INTERFACECRM_OCT.INTERFACECRMMETODO IS 'Metodo da Interface CRM - 1-ATIVAR 2-CANCELAR';

COMMENT ON COLUMN INTERFACECRM_OCT.INTERFACECRMSESSIONID IS 'Numero da Sessão da Interface CRM OCT';

COMMENT ON COLUMN INTERFACECRM_OCT.INTERFACECRMMSG IS 'Mensagem de Erro';

COMMENT ON COLUMN INTERFACECRM_OCT.INTERFACECRMLINHA IS 'Linha da Interface CRM OCT';

COMMENT ON COLUMN INTERFACECRM_OCT.INTERFACECRMDATAGERACAO IS 'Data de geração';

COMMENT ON COLUMN INTERFACECRM_OCT.INTERFACECRMDATAENVIO IS 'Data de envio';

COMMENT ON COLUMN INTERFACECRM_OCT.ID_ARQUIVOIMPORTACAO IS 'Identificação do arquivo';


--
-- INTERFACECRM_PK  (Index) 
--
CREATE UNIQUE INDEX INTERFACECRM_PK ON INTERFACECRM_OCT
(ID_INTERFACECRM)
LOGGING
TABLESPACE TSIBFF01
NOPARALLEL;


-- 
-- Non Foreign Key Constraints for Table INTERFACECRM_OCT 
-- 
ALTER TABLE INTERFACECRM_OCT ADD (
  CONSTRAINT INTERFACECRM_PK
 PRIMARY KEY
 (ID_INTERFACECRM)
    USING INDEX 
    TABLESPACE TSIBFF01);

GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACECRM_OCT TO APP_BFFOWN;

