--
-- INTERFACECRM_OCT_ERRO  (Table) 
--
CREATE TABLE INTERFACECRM_OCT_ERRO
(
  INTERFACECRM_ERRODESCRICAO  VARCHAR2(300 BYTE) NOT NULL,
  INTERFACECRM_ERROMETODO     VARCHAR2(30 BYTE) NOT NULL
)
TABLESPACE TSDSVA01
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE INTERFACECRM_OCT_ERRO IS 'Tabela de parametrização do mapa CRM.';

COMMENT ON COLUMN INTERFACECRM_OCT_ERRO.INTERFACECRM_ERRODESCRICAO IS 'Descrição';

COMMENT ON COLUMN INTERFACECRM_OCT_ERRO.INTERFACECRM_ERROMETODO IS 'Métodos';


--
-- INTERFACECRM_ERRO_PK  (Index) 
--
CREATE UNIQUE INDEX INTERFACECRM_ERRO_PK ON INTERFACECRM_OCT_ERRO
(INTERFACECRM_ERRODESCRICAO, INTERFACECRM_ERROMETODO)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACECRM_OCT_ERRO TO APP_SVAUSR;

