--
-- LOGIMPORTACAO_OCT  (Table) 
--
CREATE TABLE LOGIMPORTACAO_OCT
(
  ID_LOGIMPORTACAO             NUMBER           NOT NULL,
  ID_ARQUIVOIMPORTACAO         NUMBER           NOT NULL,
  LOGIMPORTACAONRLINHA         NUMBER           NOT NULL,
  LOGIMPORTACAOLINHA           VARCHAR2(4000 BYTE) NOT NULL,
  LOGIMPORTACAOXML             VARCHAR2(4000 BYTE),
  LOGIMPORTACAOSTATUS          NUMBER(1)        NOT NULL,
  LOGIMPORTACAOMENSAGEM        VARCHAR2(200 BYTE),
  LOGIMPORTACAODATA            DATE             NOT NULL,
  LOGIMPORTACAOTERMINAL        VARCHAR2(200 BYTE),
  LOGIMPORTACAONRDOCUMENTO     VARCHAR2(200 BYTE),
  ID_EMPRESA                   NUMBER,
  LOGIMPORTACAOTIPOARQUIVO     CHAR(1 BYTE),
  LOGIMPORTACAODATAHORAEVENTO  NUMBER,
  LOGIMPORTACAOSUFIXO          NUMBER
)
TABLESPACE TSISVA01
PARTITION BY RANGE (LOGIMPORTACAODATA)
(  
  PARTITION LOGDATA_MENOR_2014 VALUES LESS THAN (TO_DATE(' 2014-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART01,  
  PARTITION LOGDATA_2014 VALUES LESS THAN (TO_DATE(' 2015-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART02,  
  PARTITION LOGDATA_2015 VALUES LESS THAN (TO_DATE(' 2016-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART03,  
  PARTITION LOGDATA_2016 VALUES LESS THAN (TO_DATE(' 2017-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART04,  
  PARTITION LOGDATA_2017 VALUES LESS THAN (TO_DATE(' 2018-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART05,  
  PARTITION LOGDATA_2018 VALUES LESS THAN (TO_DATE(' 2019-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART06,  
  PARTITION LOGDATA_2019 VALUES LESS THAN (TO_DATE(' 2020-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART07,  
  PARTITION LOGDATA_2020 VALUES LESS THAN (TO_DATE(' 2021-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART08,  
  PARTITION LOGDATA_2021 VALUES LESS THAN (TO_DATE(' 2022-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART09,  
  PARTITION LOGDATA_MAIOR_2021 VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSDSVA_PART10
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LOGIMPORTACAO_OCT IS 'Tabela de conteudo do arquivo de importação';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.ID_LOGIMPORTACAO IS 'Chave';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.ID_ARQUIVOIMPORTACAO IS 'Chave do arquivo';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAONRLINHA IS 'Numero de linha';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAOLINHA IS 'Conteudo da linha';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAOXML IS 'Conteudo em formato XML';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAOSTATUS IS '0-Erro 1-OK 9-Em processamento';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAOMENSAGEM IS 'Mensagem de erro';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAODATA IS 'Data da importação';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAOTERMINAL IS 'Numero do terminal';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAONRDOCUMENTO IS 'Numero do documento';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.ID_EMPRESA IS 'Identificação da Empresa';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAOTIPOARQUIVO IS 'Tipo do arquivo (C-cadastro, I-inativação e M-movimento)';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAODATAHORAEVENTO IS 'Data e Hora do evento no formato AAAAMMDDHHMMSS';

COMMENT ON COLUMN LOGIMPORTACAO_OCT.LOGIMPORTACAOSUFIXO IS 'Sufixo do numero do terminal para ser utilizado no fatiamento do sonsumo';


--
-- LOGIMPORTACAONX1  (Index) 
--
CREATE INDEX LOGIMPORTACAONX1_OCT ON LOGIMPORTACAO_OCT
(LOGIMPORTACAOTERMINAL, LOGIMPORTACAOSTATUS)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


--
-- LOGIMPORTACAONX2  (Index) 
--
CREATE INDEX LOGIMPORTACAONX2_OCT ON LOGIMPORTACAO_OCT
(ID_ARQUIVOIMPORTACAO)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


--
-- LOGIMPORTACAONX3  (Index) 
--
CREATE INDEX LOGIMPORTACAONX3_OCT ON LOGIMPORTACAO_OCT
(SUBSTR("LOGIMPORTACAOLINHA",1,1), LOGIMPORTACAOSTATUS, LOGIMPORTACAOTIPOARQUIVO)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


--
-- LOGIMPORTACAO_PK  (Index) 
--
CREATE UNIQUE INDEX LOGIMPORTACAO_OCT_PK ON LOGIMPORTACAO_OCT
(ID_LOGIMPORTACAO)
LOGGING
TABLESPACE TSISVA01
NOPARALLEL;


-- 
-- Non Foreign Key Constraints for Table LOGIMPORTACAO_OCT 
-- 
ALTER TABLE LOGIMPORTACAO_OCT ADD (
  CONSTRAINT LOGIMPORTACAO_OCT_PK
 PRIMARY KEY
 (ID_LOGIMPORTACAO)
    USING INDEX 
    TABLESPACE TSISVA01);

GRANT DELETE, INSERT, SELECT, UPDATE ON LOGIMPORTACAO_OCT TO APP_BFFOWN;

